FROM python:3.12-slim
WORKDIR /app
# Copy the service folder
COPY ./auth_service /app/auth_service
# Install dependencies
RUN pip install --no-cache-dir -r /app/auth_service/requirements.txt
# Start app correctly (use the package path!)
CMD ["uvicorn", "auth_service.auth_main:app", "--host", "0.0.0.0", "--port", "8001"]
