FROM python:3.12-slim

WORKDIR /app
# Copy the service folder
COPY ./employee_service /app/employee_service
# Install dependencies
RUN pip install --no-cache-dir -r /app/employee_service/requirements.txt
# Start app correctly (use the package path!)
CMD ["uvicorn", "employee_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
