FROM python:3.12-slim
WORKDIR /app
RUN pip install fastapi uvicorn google-cloud-pubsub google-cloud-firestore python-dotenv uuid redis json asyncio logging
COPY app.py .
CMD [ "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8082" ]