services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRESDB: notesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - notes-net'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d notesdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  notes-a:
    image: notes-multi:latest
    environment:
      DATABASE_URL: postgresql://user:${POSTGRES_PASSWORD}@db:5432/notesdb
    volumes:
      - notes_data:/app/data
    networks:
      - notes-net
    ports:
      - "5000:5000"
    secrets:
      - db_password
      - notes_encrypt_key
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  db_password:
    file: ./secrets/db_pass.txt
  notes_encrypt_key:
    file: ./secrets/notes_key.txt

volumes:
  db_data:
  notes_data:

networks:
  notes-net:
    driver: bridge


# add a service that will start a postgres container and that container should expose to 5432
