FROM python:3.12-slim
WORKDIR /app
# Copy the service folder
COPY ./notification_service /app/notification_service
# Install dependencies
RUN pip install --no-cache-dir -r /app/notification_service/requirements.txt
# Start app correctly (use the package path!)
CMD ["uvicorn", "notification_service.main:app", "--host", "0.0.0.0", "--port", "8002"]
