version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - "16686:16686"
      - "14317:4317"
      - "14318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OTEL_SERVICE_NAME=flask-app
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - jaeger